[deploy]
bucket = 'cfn-artifacts-hs'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:850249732638:certificate/e5151f8a-b649-486f-887a-f6d51e35c027'
